# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitter_server}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["technoweenie"]
  s.date = %q{2009-12-19}
  s.description = %q{Twitter API implementation on top of Sinatra}
  s.email = %q{technoweenie@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "demo/faker_server.rb",
     "lib/renderers/nokogiri_renderer.rb",
     "lib/twitter_server.rb",
     "test/helper.rb",
     "test/sinatra/account_test.rb",
     "test/sinatra/basic_auth_test.rb",
     "test/sinatra/help_test.rb",
     "test/sinatra/statuses_test.rb",
     "twitter_server.gemspec"
  ]
  s.homepage = %q{http://github.com/technoweenie/twitter_server}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Twitter API implementation on top of Sinatra}
  s.test_files = [
    "test/helper.rb",
     "test/sinatra/account_test.rb",
     "test/sinatra/basic_auth_test.rb",
     "test/sinatra/help_test.rb",
     "test/sinatra/statuses_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<context>, [">= 0"])
    else
      s.add_dependency(%q<context>, [">= 0"])
    end
  else
    s.add_dependency(%q<context>, [">= 0"])
  end
end

